[[language]]
name = "rust"
auto-format = false

[[language]]
name = "typescript"
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

[language-server.rust-analyzer.config.check]
command = "clippy"
