[[language]]
name = "rust"
auto-format = false

[[language]]
name = "dart"
auto-format = false

[[language]]
name = "typescript"
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }


[[language]]
name = "gopls"
auto-format = true

[[language]]
name = "pylsp"

[[language]]
name = "clangd"

[[language]]
name = "bash-language-server"
scope = "source.bashrc"

[[language]]
name = "typescript-language-server"
auto-format = false

[language-server.rust-analyzer.config.check]
command = "clippy"
